name: Bump Add-on Version and Build
on:
  push:
    branches:
      - main
    paths:
      - 'trip_logger/requirements.txt' # Triggers only when dependencies change

jobs:
  update-addon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup yq
        uses: mikefarah/yq@master

      - name: Bump Version in config.yaml
        run: |
          CURRENT_VERSION=$(yq e '.version' trip_logger/config.yaml)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')

          yq e -i ".version = \"$NEW_VERSION\"" trip_logger/config.yaml
          echo "Updated config.yaml from $CURRENT_VERSION to $NEW_VERSION"

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add trip_logger/config.yaml
          git commit -m "chore: bump add-on version for dependency update"
          git push
