name: "Hyndai/Kia/Genesis Trip Logger"
version: "1.0.14"
slug: "trip_logger"
description: "Automatically pulls daily trip logs from Kia Connect and saves them to a CSV."
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
map:
  - share:rw
options:
  username: "your_email@example.com"
  password: "your_password"
  folder: "/share/"
  region: "AUSTRALIA"
  brand: "KIA"
schema:
  username: str
  password: password
  folder: str
  region: "list(EUROPE|CANADA|USA|CHINA|AUSTRALIA|INDIA|NZ|BRAZIL)"
  brand: "list(KIA|HYUNDAI|GENESIS)"
